export const MENU_UPDATE = 'MENU_UPDATE';
export const MENU_MODIFY_ITEM_COUNT = 'MENU_MODIFY_ITEM_COUNT';
export const MENU_MODIFY_ITEM_COUNT_WITH_SPEC = 'MENU_MODIFY_ITEM_COUNT_WITH_SPEC';
export const MENU_EMPTY_BASKET = 'MENU_EMPTY_BASKET';
export const MENU_OPEN_DETAIL = 'MENU_OPEN_DETAIL';
export const MENU_CLOSE_DETAIL = 'MENU_CLOSE_DETAIL';
